### PR TITLE
Make server capabilities configurable

### PR DESCRIPTION
**Pull request by achim-k**
**Public-Facing Changes**
None

**Description**
- Allows to pass in server capabilities as argument

### CODE REVIEW

**Comment by jhurliman** [comment]
Does this mean the websocket_server code will need to look at this list of capabilities to decide what features to toggle on/off?

**Comment by jtbandes** [comment]
> Does this mean the websocket_server code will need to look at this list of capabilities to decide what features to toggle on/off?

+1, seems like it could make sense to have a server configuration where you can toggle client publishing on/off, and the server translates that to a capability? Or what were you envisioning?

**Comment by achim-k** [comment]
> Does this mean the websocket_server code will need to look at this list of capabilities to decide what features to toggle on/off?

Yes, the server will have to check if an operation is allowed to be called based on its capabilities. Is this what you mean?

**Comment by achim-k** [comment]
Closing as this got merged with #114

**Pull request closed without merging**
